using System;
using System.Collections.Generic;
using System.Numerics;
using NotBSRenderer;

namespace BlueSky.Animation.AnimScript;

/// <summary>
/// Visual flowchart editor for AnimScript.
/// Allows creating animation state machines visually with nodes and connections.
/// </summary>
public class AnimScriptFlowchartEditor
{
    private AnimStateMachine _stateMachine = new();
    private List<StateNode> _nodes = new();
    private List<TransitionEdge> _edges = new();
    
    private StateNode? _selectedNode = null;
    private StateNode? _draggedNode = null;
    private Vector2 _dragOffset;
    
    private bool _isConnecting = false;
    private StateNode? _connectionStart = null;
    
    public bool IsOpen { get; set; } = false;
    
    /// <summary>
    /// Load AnimScript into flowchart editor
    /// </summary>
    public void Load(AnimStateMachine stateMachine)
    {
        _stateMachine = stateMachine;
        _nodes.Clear();
        _edges.Clear();
        
        // Create nodes for each state
        int index = 0;
        foreach (var kvp in stateMachine.States)
        {
            var node = new StateNode
            {
                State = kvp.Value,
                Position = new Vector2(100 + (index % 3) * 250, 100 + (index / 3) * 200)
            };
            _nodes.Add(node);
            index++;
        }
        
        // Create edges for transitions
        foreach (var node in _nodes)
        {
            foreach (var transition in node.State.Transitions)
            {
                var targetNode = _nodes.Find(n => n.State.Name == transition.TargetState);
                if (targetNode != null)
                {
                    _edges.Add(new TransitionEdge
                    {
                        From = node,
                        To = targetNode,
                        Transition = transition
                    });
                }
            }
        }
        
        Console.WriteLine($"[AnimScript] Loaded {_nodes.Count} states into flowchart");
    }
    
    /// <summary>
    /// Save flowchart back to AnimScript text
    /// </summary>
    public string SaveToScript()
    {
        var script = new System.Text.StringBuilder();
        script.AppendLine("// Generated by AnimScript Flowchart Editor");
        script.AppendLine();
        
        foreach (var node in _nodes)
        {
            var state = node.State;
            script.AppendLine($"state {state.Name} {{");
            script.AppendLine($"    animation \"{state.AnimationName}\"");
            script.AppendLine($"    speed {state.Speed}");
            script.AppendLine($"    loop {(state.Loop ? "true" : "false")}");
            script.AppendLine($"    blend {state.BlendTime}");
            script.AppendLine();
            
            foreach (var transition in state.Transitions)
            {
                script.Append($"    transition {transition.TargetState} when ");
                script.AppendLine(ConditionToString(transition.Condition));
            }
            
            script.AppendLine("}");
            script.AppendLine();
        }
        
        return script.ToString();
    }
    
    /// <summary>
    /// Render the flowchart editor
    /// </summary>
    public void Render(NotBSUI ui, float x, float y, float width, float height)
    {
        if (!IsOpen) return;
        
        // Background
        ui.RoundedPanel(x, y, width, height, new Vector4(0.12f, 0.12f, 0.14f, 1), 8f);
        
        // Title bar
        ui.RoundedGradientPanel(x, y, width, 40,
            new Vector4(0.2f, 0.3f, 0.5f, 1),
            new Vector4(0.15f, 0.25f, 0.45f, 1), 8f);
        
        float canvasX = x + 10;
        float canvasY = y + 50;
        float canvasW = width - 20;
        float canvasH = height - 60;
        
        // Canvas background (grid)
        ui.RoundedPanel(canvasX, canvasY, canvasW, canvasH, new Vector4(0.08f, 0.08f, 0.1f, 1), 6f);
        
        // Draw grid
        DrawGrid(ui, canvasX, canvasY, canvasW, canvasH);
        
        // Draw edges (transitions)
        foreach (var edge in _edges)
        {
            DrawEdge(ui, edge, canvasX, canvasY);
        }
        
        // Draw nodes (states)
        foreach (var node in _nodes)
        {
            DrawNode(ui, node, canvasX, canvasY);
        }
        
        // Draw connection line if connecting
        if (_isConnecting && _connectionStart != null)
        {
            // TODO: Draw line from connection start to mouse
        }
        
        // Toolbar
        DrawToolbar(ui, x, y + height - 50, width, 50);
    }
    
    private void DrawGrid(NotBSUI ui, float x, float y, float width, float height)
    {
        float gridSize = 50;
        var gridColor = new Vector4(0.15f, 0.15f, 0.17f, 1);
        
        // Vertical lines
        for (float gx = 0; gx < width; gx += gridSize)
        {
            ui.Panel(x + gx, y, 1, height, gridColor);
        }
        
        // Horizontal lines
        for (float gy = 0; gy < height; gy += gridSize)
        {
            ui.Panel(x, y + gy, width, 1, gridColor);
        }
    }
    
    private void DrawNode(NotBSUI ui, StateNode node, float canvasX, float canvasY)
    {
        float nodeX = canvasX + node.Position.X;
        float nodeY = canvasY + node.Position.Y;
        float nodeW = 180;
        float nodeH = 100;
        
        bool isSelected = node == _selectedNode;
        
        // Node shadow
        ui.Shadow(nodeX, nodeY, nodeW, nodeH, 3, 3, 0.4f);
        
        // Node background
        var bgColor = isSelected 
            ? new Vector4(0.3f, 0.5f, 0.7f, 1) 
            : new Vector4(0.2f, 0.22f, 0.25f, 1);
        
        ui.RoundedPanel(nodeX, nodeY, nodeW, nodeH, bgColor, 8f);
        
        // Node header (state name)
        ui.RoundedGradientPanel(nodeX, nodeY, nodeW, 30,
            new Vector4(0.25f, 0.35f, 0.45f, 1),
            new Vector4(0.2f, 0.3f, 0.4f, 1), 8f);
        
        // State info (animation name, speed, loop)
        // Note: NotBSUI doesn't support text positioning, so we skip text for now
        
        // Connection points (input/output)
        float portSize = 12;
        
        // Input port (top)
        ui.Circle(nodeX + nodeW / 2, nodeY, portSize / 2, new Vector4(0.4f, 0.8f, 0.4f, 1), true);
        
        // Output port (bottom)
        ui.Circle(nodeX + nodeW / 2, nodeY + nodeH, portSize / 2, new Vector4(0.8f, 0.4f, 0.4f, 1), true);
    }
    
    private void DrawEdge(NotBSUI ui, TransitionEdge edge, float canvasX, float canvasY)
    {
        float fromX = canvasX + edge.From.Position.X + 90; // Center of node
        float fromY = canvasY + edge.From.Position.Y + 100; // Bottom of node
        
        float toX = canvasX + edge.To.Position.X + 90;
        float toY = canvasY + edge.To.Position.Y; // Top of node
        
        // Draw arrow line
        var lineColor = new Vector4(0.6f, 0.6f, 0.7f, 1);
        ui.Line(fromX, fromY, toX, toY, lineColor);
        
        // Draw arrowhead
        float arrowSize = 8;
        float angle = MathF.Atan2(toY - fromY, toX - fromX);
        
        float arrowX1 = toX - arrowSize * MathF.Cos(angle - 0.5f);
        float arrowY1 = toY - arrowSize * MathF.Sin(angle - 0.5f);
        
        float arrowX2 = toX - arrowSize * MathF.Cos(angle + 0.5f);
        float arrowY2 = toY - arrowSize * MathF.Sin(angle + 0.5f);
        
        ui.Line(toX, toY, arrowX1, arrowY1, lineColor);
        ui.Line(toX, toY, arrowX2, arrowY2, lineColor);
    }
    
    private void DrawToolbar(NotBSUI ui, float x, float y, float width, float height)
    {
        ui.RoundedPanel(x, y, width, height, new Vector4(0.15f, 0.15f, 0.17f, 1), 6f);
        
        float btnX = x + 10;
        float btnY = y + 10;
        float btnW = 100;
        float btnH = 30;
        
        var normalColor = new Vector4(0.25f, 0.35f, 0.45f, 1);
        var hoverColor = new Vector4(0.3f, 0.4f, 0.5f, 1);
        var pressedColor = new Vector4(0.2f, 0.3f, 0.4f, 1);
        var shadowColor = new Vector4(0, 0, 0, 0.3f);
        var textColor = new Vector4(0.9f, 0.9f, 0.9f, 1);
        
        // Add State button
        if (ui.ButtonEx(btnX, btnY, btnW, btnH, "Add State",
            normalColor, hoverColor, pressedColor, shadowColor, textColor))
        {
            AddNewState();
        }
        
        btnX += btnW + 10;
        
        // Delete State button
        if (ui.ButtonEx(btnX, btnY, btnW, btnH, "Delete",
            new Vector4(0.6f, 0.2f, 0.2f, 1), new Vector4(0.7f, 0.25f, 0.25f, 1),
            pressedColor, shadowColor, textColor))
        {
            DeleteSelectedState();
        }
        
        btnX += btnW + 10;
        
        // Save button
        if (ui.ButtonEx(btnX, btnY, btnW, btnH, "Save Script",
            new Vector4(0.2f, 0.6f, 0.3f, 1), new Vector4(0.25f, 0.7f, 0.35f, 1),
            pressedColor, shadowColor, textColor))
        {
            SaveToFile();
        }
    }
    
    private void AddNewState()
    {
        var newState = new AnimState
        {
            Name = $"State{_nodes.Count + 1}",
            AnimationName = "animation_name",
            Speed = 1.0f,
            Loop = true,
            BlendTime = 0.2f
        };
        
        var newNode = new StateNode
        {
            State = newState,
            Position = new Vector2(100, 100)
        };
        
        _nodes.Add(newNode);
        _stateMachine.States[newState.Name] = newState;
        
        Console.WriteLine($"[AnimScript] Added new state: {newState.Name}");
    }
    
    private void DeleteSelectedState()
    {
        if (_selectedNode == null) return;
        
        _nodes.Remove(_selectedNode);
        _stateMachine.States.Remove(_selectedNode.State.Name);
        
        // Remove edges connected to this node
        _edges.RemoveAll(e => e.From == _selectedNode || e.To == _selectedNode);
        
        Console.WriteLine($"[AnimScript] Deleted state: {_selectedNode.State.Name}");
        _selectedNode = null;
    }
    
    private void SaveToFile()
    {
        string script = SaveToScript();
        string path = "generated_animscript.anim";
        System.IO.File.WriteAllText(path, script);
        Console.WriteLine($"[AnimScript] Saved to: {path}");
    }
    
    private string ConditionToString(AnimCondition condition)
    {
        if (condition is VariableCondition varCond)
        {
            string op = varCond.Operator switch
            {
                ComparisonOp.Greater => ">",
                ComparisonOp.GreaterEqual => ">=",
                ComparisonOp.Less => "<",
                ComparisonOp.LessEqual => "<=",
                ComparisonOp.Equal => "==",
                ComparisonOp.NotEqual => "!=",
                _ => ">"
            };
            return $"{varCond.VariableName} {op} {varCond.Value}";
        }
        else if (condition is BoolCondition boolCond)
        {
            return boolCond.VariableName;
        }
        
        return "true";
    }
    
    /// <summary>
    /// Handle mouse input for node dragging and selection
    /// </summary>
    public void HandleInput(Vector2 mousePos, bool mouseDown, bool mouseReleased)
    {
        // TODO: Implement mouse interaction
        // - Click to select node
        // - Drag to move node
        // - Click output port to start connection
        // - Click input port to complete connection
    }
}

/// <summary>
/// Visual node representing an animation state
/// </summary>
internal class StateNode
{
    public AnimState State { get; set; } = null!;
    public Vector2 Position { get; set; }
}

/// <summary>
/// Visual edge representing a transition
/// </summary>
internal class TransitionEdge
{
    public StateNode From { get; set; } = null!;
    public StateNode To { get; set; } = null!;
    public AnimTransition Transition { get; set; } = null!;
}
